config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :processings, except: %i[edit update create new destroy] do
    resources :analyses, except: %i[edit update] do
      post "/redo_analysis", to: "analyses#redo_analysis"
    end
  end

  resources :qrcode, only: [:index] do
  end
  get "/qrcode/generate", controller: "qrcode#generate", as: "qrcode_generate"

  resources :preprocessings do
    post "/redo_preprocessing", to: "preprocessings#redo_preprocessing"
  end

  resources :documents do
    resources :input_files, except: [:index]
    post "/process_archive", to: "documents#process_archive"
  end

  post "/preprocessed_data", to: "preprocessings_data#preprocessed_data"
  post "/analysis_data", to: "analyses_data#store_analysis_data"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations"
  }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    get "/debug", to: "pages#debug"
  end

  root to: "pages#home"
end

app/views/pages/debug.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Welcome to OSP toolbox</h1>
    </div>
  </div>
  <div class="row">
    <% @services.each do |service| %>
      <div class="col-4">
        <div class="card alert-success <%= "alert-danger" unless service[:status].code == "200" %>">
          <div class="card-body">
            <h2 class="card-title">Name: <%= service[:name] %></h2>
            <p class="card-text">
              Code: <%= service[:status].code %>
              <br>
              Body: <%= display_pretty_json(service[:status].body) %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Welcome to OSP toolbox</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to documents_path, class: "card-actions" do %>
        <div class="card text-center">
          <%= image_tag "document.svg", class: "card-img-top", alt: t(".comments_mapping.alt") %>
          <div class="card-body">
            <h2 class="card-title"><%= t(".comments_mapping.title") %></h2>
            <p class="card-text">
              <%= t(".comments_mapping.description") %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col">
      <%= link_to preprocessings_path, class: "card-actions" do %>
        <div class="card text-center">
          <%= image_tag "services.svg", class: "card-img-top", alt: t(".preprocessings.alt") %>
          <div class="card-body">
            <h2 class="card-title"><%= t(".preprocessings.title") %></h2>
            <p class="card-text">
              <%= t(".preprocessings.description") %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col">
      <%= link_to processings_path, class: "card-actions" do %>
        <div class="card text-center">
          <%= image_tag "ring-details.svg", class: "card-img-top", alt: t(".exploratory_data_analysis.alt") %>
          <div class="card-body">
            <h2 class="card-title"><%= t(".exploratory_data_analysis.title") %></h2>
            <p class="card-text">
              <%= t(".exploratory_data_analysis.description") %>
            </p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col">
      <%= link_to qrcode_index_path, class: "card-actions" do %>
        <div class="card text-center">
          <%= render inline: Rails.root.join('app/assets/images/qrcode.svg').read %>
          <div class="card-body">
            <h2 class="card-title"><%= t(".qrcode.title") %></h2>
            <p class="card-text">
              <%= t(".qrcode.description") %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>