config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :processings, except: %i[edit update create new destroy] do
    resources :analyses, except: %i[edit update] do
      post "/redo_analysis", to: "analyses#redo_analysis"
    end
  end

  resources :qrcode, only: [:index] do
  end
  get "/qrcode/generate", controller: "qrcode#generate", as: "qrcode_generate"

  resources :preprocessings do
    post "/redo_preprocessing", to: "preprocessings#redo_preprocessing"
  end

  resources :documents do
    resources :input_files, except: [:index]
    post "/process_archive", to: "documents#process_archive"
  end

  post "/preprocessed_data", to: "preprocessings_data#preprocessed_data"
  post "/analysis_data", to: "analyses_data#store_analysis_data"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations"
  }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    get "/debug", to: "pages#debug"
  end

  root to: "pages#home"
end

app/models/document.rb
# frozen_string_literal: true

# Document class
class Document < ApplicationRecord
  belongs_to :user
  has_many :input_files, dependent: :destroy
  has_one :archive, dependent: :destroy

  validates :title, presence: true

  def process_archive
    return unless input_files.size >= 2

    ProcessDocumentJob.perform_later(id)
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

# Documents controller
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[process_archive show edit update destroy]

  # GET /documents or /documents.json
  def index
    @query = Document.ransack(params[:q])
    @documents = @query.result(distinct: true).page(params[:page])
  end

  # GET /documents/1 or /documents/1.json
  def show; end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit; end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params.merge(user: current_user))

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: t(".create") }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: t(".update") }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: t(".destroy") }
      format.json { head :no_content }
    end
  end

  def process_archive
    ProcessDocumentJob.perform_later(@document.id)

    respond_to do |format|
      format.html { redirect_to document_path(@document), notice: t(".process_archive") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params.try(:[], :id) || params.try(:[], :document_id))
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params.require(:document).permit(:title, :ready)
  end
end

app/helpers/documents_helper.rb
# frozen_string_literal: true

# Helper for documents
module DocumentsHelper
  def document_archive_for(document)
    if document.archive && document.archive.file.present?
      link_to t("download", filename: document.archive.file.name, scope: "documents_helper.document_archive_for"),
              rails_blob_path(document.archive.file, disposition: "attachment"),
              class: "btn btn-outline-success"

    else
      t("no_available_archive", scope: "documents_helper.document_archive_for")
    end
  end

  def process_archive_for(document)
    return unless ready_to_process?(document)

    render partial: "process_archive_button"
  end

  def ready_to_process?(document)
    document.input_files&.count == 2
  end
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit t(".submit"), class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/documents/_process_archive_button.erb
<%= form_with(url: document_process_archive_path(document_id: @document), method: :post) do |form| %>
  <%= form.submit t(".submit"), class: "btn btn-outline-primary" %>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render "form", document: @document %>

<%= link_to "Show", @document %> |
<%= link_to "Back", documents_path %>

app/views/documents/index.html.erb
<div class="row">
  <div class="col">
    <h1>Documents</h1>
  </div>
</div>

<%= render "shared/search", search_query: :title_cont do %>
  <%= link_to "New Document", new_document_path, class: "btn btn-outline-primary" %>
<% end %>

<div class="row">
  <table class="table">
    <thead>
    <tr>
      <th><%= sort_link(@query, :title) %></th>
      <th><%= sort_link(@query, :user) %></th>
      <th><%= sort_link(@query, :ready) %></th>
      <th>Archive</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.user.nickname %></td>
        <td><%= ready_to_process?(document) %></td>
        <td>
          <%= document_archive_for(document) %>
        </td>
        <td>
          <div class="row">
            <div class="col">
              <%= link_to "Show",
                          document,
                          class: "btn btn-outline-success" %>
            </div>
            <div class="col">
              <%= link_to "Edit",
                          edit_document_path(document),
                          class: "btn btn-outline-secondary" %>
            </div>
            <div class="col">
              <%= link_to "Destroy",
                          document,
                          method: :delete,
                          data: { confirm: "Are you sure?" },
                          class: "btn btn-outline-danger" %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @documents %>
</div>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render "form", document: @document %>
<%= link_to "Back", documents_path %>

app/views/documents/show.html.erb
<h1>Document: <%= @document.title %></h1>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @document.user.email %>
</p>

<%= render partial: "input_files/list", locals: { input_files: @document.input_files } %>

<%= document_archive_for @document %>

<%= process_archive_for(@document) %>

<%= link_to "Edit", edit_document_path(@document) %> |
<%= link_to "Back", documents_path %>