config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :processings, except: %i[edit update create new destroy] do
    resources :analyses, except: %i[edit update] do
      post "/redo_analysis", to: "analyses#redo_analysis"
    end
  end

  resources :qrcode, only: [:index] do
  end
  get "/qrcode/generate", controller: "qrcode#generate", as: "qrcode_generate"

  resources :preprocessings do
    post "/redo_preprocessing", to: "preprocessings#redo_preprocessing"
  end

  resources :documents do
    resources :input_files, except: [:index]
    post "/process_archive", to: "documents#process_archive"
  end

  post "/preprocessed_data", to: "preprocessings_data#preprocessed_data"
  post "/analysis_data", to: "analyses_data#store_analysis_data"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations"
  }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    get "/debug", to: "pages#debug"
  end

  root to: "pages#home"
end

app/models/input_file.rb
# frozen_string_literal: true

# Intput file stores a file to be used with documents
class InputFile < ApplicationRecord
  has_one_attached :file
  belongs_to :document
  after_commit :trigger_archive_processing

  validates :file, attached: true, content_type: "text/csv"
  validate :only_one_file_by_type

  def only_one_file_by_type
    return unless document
    return true unless document.input_files.map(&:typename).include?(typename)

    errors.add(:base, "A document from #{typename} type has already been uploaded")
  end

  def trigger_archive_processing
    document.process_archive
  end
end

app/controllers/input_files_controller.rb
# frozen_string_literal: true

# Input files controller
class InputFilesController < ApplicationController
  before_action :set_input_file, only: %i[show edit update destroy]
  before_action :document

  # GET /input_files/1 or /input_files/1.json
  def show; end

  # GET /input_files/new
  def new
    @input_file = InputFile.new
  end

  # GET /input_files/1/edit
  def edit; end

  # POST /input_files or /input_files.json
  def create
    @input_file = InputFile.new(input_file_params.merge(document:))

    respond_to do |format|
      if @input_file.save
        format.html { redirect_to document_path(id: @document), notice: create_notice_message }
        format.json { render :show, status: :created, location: @input_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @input_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /input_files/1 or /input_files/1.json
  def update
    respond_to do |format|
      if @input_file.update(input_file_params)
        format.html { redirect_to document_input_file_path(id: @input_file), notice: t(".update") }
        format.json { render :show, status: :ok, location: @input_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @input_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /input_files/1 or /input_files/1.json
  def destroy
    @input_file.destroy
    respond_to do |format|
      format.html { redirect_to document_path(id: @document), notice: t(".destroy") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_input_file
    @input_file = InputFile.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def input_file_params
    params.require(:input_file).permit(:file, :typename)
  end

  def document
    @document = Document.find(params[:document_id])
  end

  def create_notice_message
    if document.input_files.count < 2
      t(".create_notice_message.singular")
    else
      t(".create_notice_message.plural")
    end
  end
end

app/helpers/input_files_helper.rb
# frozen_string_literal: true

# Helper for input files
module InputFilesHelper
end

app/views/input_files/_form.html.erb
<%= form_with(model: [@document, @input_file], url: document_input_files_path) do |form| %>
  <% if input_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(input_file.errors.count, "error") %> prohibited this input_file from being saved:</h2>

      <ul>
        <% input_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="field">
    <%= form.label :typename %>
    <%= form.select :typename, ["Proposals", "Comments"] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/input_files/_list.html.erb
<h2>Input Files</h2>

<table class="table">
  <thead>
  <tr>
    <th>File</th>
    <th>Typename</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% input_files.each do |input_file| %>
    <tr>
      <td>
        <% if input_file.file.attachment %>
          <%= link_to "Download #{input_file.file.name}", rails_blob_path(input_file.file, disposition: "attachment") %>
        <% else %>
          Attachment is missing
        <% end %>
      </td>
      <td><%= input_file.typename %></td>
      <td><%= link_to "Show", document_input_file_path(document_id: input_file.document_id, id: input_file) %></td>
      <td><%= link_to "Edit", edit_document_input_file_path(document_id: input_file.document_id, id: input_file) %></td>
      <td><%= link_to "Destroy", document_input_file_path(document_id: input_file.document_id, id: input_file), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% unless ready_to_process?(@document) %>
<%= link_to "New Input File", new_document_input_file_path(@document) %>
<% end %>

app/views/input_files/edit.html.erb
<h1>Editing Input File</h1>

<%= render "form", input_file: @input_file %>

<%= link_to "Show", document_input_file_path(@input_file) %> |
<%= link_to "Back", document_path(@document) %>

app/views/input_files/new.html.erb
<h1>New Input File</h1>

<%= render "form", input_file: @input_file %>

<%= link_to "Back", document_path(@document) %>

app/views/input_files/show.html.erb
<p>
  <strong>File:</strong>
  <%= link_to @input_file.file.filename, @input_file.file if @input_file.file.attached? %>
</p>

<p>
  <strong>Type:</strong>
  <%= @input_file.typename %>
</p>

<%= link_to "Edit", edit_document_input_file_path(id: @input_file) %> |
<%= link_to "Back", document_path(@document) %>