config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :processings, except: %i[edit update create new destroy] do
    resources :analyses, except: %i[edit update] do
      post "/redo_analysis", to: "analyses#redo_analysis"
    end
  end

  resources :qrcode, only: [:index] do
  end
  get "/qrcode/generate", controller: "qrcode#generate", as: "qrcode_generate"

  resources :preprocessings do
    post "/redo_preprocessing", to: "preprocessings#redo_preprocessing"
  end

  resources :documents do
    resources :input_files, except: [:index]
    post "/process_archive", to: "documents#process_archive"
  end

  post "/preprocessed_data", to: "preprocessings_data#preprocessed_data"
  post "/analysis_data", to: "analyses_data#store_analysis_data"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations"
  }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    get "/debug", to: "pages#debug"
  end

  root to: "pages#home"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "icon.svg", width: "auto", height: "50px" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Comments mapping", documents_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Preprocessings", preprocessings_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Exploratory data analysis", processings_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to t(".sidekiq"), "/sidekiq", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to t(".debug"), debug_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to t(".edit_profile"), edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OspToolbox</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>
</head>

<body>
<%= render "layouts/navbar" %>
<%= render "shared/flash_messages" %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>